export const START_LOADING_CURRENCY_RATES =
  "currencyRates/START_LOADING_CURRENCY_RATES";
export const SET_CURRENCY_RATES_ERROR =
  "currencyRates/SET_CURRENCY_RATES_ERROR";
export const SET_CURRENCY_RATES = "currency-rates/SET_CURRENCY_RATES";
